<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\UrlRule;

class SyncUrlRules extends Command
{
    protected $signature = 'waf:sync-url-rules
        {file=/etc/nginx/modsec/url-rules.conf : Full path to ModSecurity URL rules file}';

    protected $description = 'Generate ModSecurity URL access rules from database';

    public function handle(): int
    {
        $file = $this->argument('file');
        $this->info("Writing URL rules to: {$file}");

        $rules = UrlRule::where('enabled', true)->get();

        $content = "# AUTO-GENERATED BY waf:sync-url-rules - DO NOT EDIT MANUALLY\n\n";

        foreach ($rules as $rule) {
            $path = trim($rule->path);
            if ($path === '') {
                continue;
            }

            // نفصل IPs بأي مسافة أو فاصلة
            $ips = preg_split('/[\s,]+/', $rule->allowed_ips, -1, PREG_SPLIT_NO_EMPTY);
            if (empty($ips)) {
                continue;
            }

            // نخليها مفصولة بمسافة (ModSecurity يقبلها)
            $ipList = implode(' ', $ips);

            // نخلي ID فريد في رينج بعيد
            $baseId = 500000;
            $ruleId = $baseId + $rule->id;
            $msg    = addslashes($rule->name ?: "Restricted URL {$path}");
            
            $host = trim($rule->host ?? '');

            // نكوّن النص سطر بسطر (بدون Heredoc عشان ما نتلخبط)
            // إذا كان هناك host محدد، نضيف شرط للـ host أولاً
            if ($host !== '') {
                // Chain rule: نتحقق من الـ host أولاً، ثم الـ path، ثم IP
                $content .= "SecRule REQUEST_HEADERS:Host \"@streq {$host}\" \\\n";
                $content .= "    \"id:{$ruleId},\\\n";
                $content .= "    phase:1,\\\n";
                $content .= "    log,\\\n";
                $content .= "    deny,\\\n";
                $content .= "    status:403,\\\n";
                $content .= "    chain,\\\n";
                $content .= "    msg:'{$msg}'\"\n";
                $content .= "    SecRule REQUEST_URI \"@beginsWith {$path}\" \\\n";
                $content .= "        \"chain\"\n";
                $content .= "    SecRule REMOTE_ADDR \"!@ipMatch {$ipList}\"\n\n";
            } else {
                // بدون host: نطبق على كل المواقع
                $content .= "SecRule REQUEST_URI \"@beginsWith {$path}\" \\\n";
                $content .= "    \"id:{$ruleId},\\\n";
                $content .= "    phase:1,\\\n";
                $content .= "    log,\\\n";
                $content .= "    deny,\\\n";
                $content .= "    status:403,\\\n";
                $content .= "    chain,\\\n";
                $content .= "    msg:'{$msg}'\"\n";
                $content .= "    SecRule REMOTE_ADDR \"!@ipMatch {$ipList}\"\n\n";
            }
        }

        if (false === @file_put_contents($file, $content)) {
            $this->error("Failed to write file: {$file}");
            return self::FAILURE;
        }

        $this->info("URL rules file written.");

        // اختياري: اختبر Nginx وأعد التحميل (يحتاج صلاحيات)
        $this->info("Testing nginx config...");
        $output = shell_exec('nginx -t 2>&1');
        $this->line($output);

        if (str_contains($output, 'test is successful')) {
            $this->info("Reloading nginx...");
            shell_exec('systemctl reload nginx');
        } else {
            $this->error("nginx test failed, NOT reloading.");
        }

        return self::SUCCESS;
    }
}
